# Lesson 3: Python for Data Analytics Using NumPy 

In [1]:
import numpy as np

In [5]:
#creating sample array
arr = np.arange(0,11)

In [6]:
#show output
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [8]:
arr[0]

0

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr[0:10]=100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10])

In [13]:
slice_of_arr=arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [14]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

<b>Indexing a 2D array (matrices)<br>
    <b>General Format: arr_2d[row] or arr_2d[row,col]

In [16]:
arr_2d = np.array(([50,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[50, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d = np.array(([50,10,15],[20,25,30],[35,40,45]))
arr_2d[1]

array([20, 25, 30])

In [21]:
arr_2d[1][0]

20

In [22]:
arr_2d[1,0]

20

In [24]:
#fancy indexing
arr2d=np.zeros((10,10))

In [25]:
arr_length=arr2d.shape[1]

In [28]:
for i in range(arr_length):
    arr2d[i]=i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [30]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

<b>Selection

In [32]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

<b>Numpy Operations

In [36]:
arr = np.arange(0,10)

In [37]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
arr *arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [40]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

<b> NumPy Arrays

In [41]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [42]:
np.array(my_list)

array([1, 2, 3])

In [43]:
my_Matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_Matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [44]:
np.array(my_Matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<b>Built-in Methods

In [45]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [50]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [51]:
#Zeroes and Ones
np.zeros(3)


array([0., 0., 0.])

In [53]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.ones(3)

array([1., 1., 1.])

In [55]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

<b>Linespace

In [57]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<b>Random

In [71]:
np.random.randint(1,100)

93

In [72]:
np.random.randint(1,100,10)

array([95, 98, 87, 88, 19, 39, 32, 61, 34, 85])

In [73]:
#Array Attributes and Methods
arr=np.arange(25)
ranarr=np.random.randint(0.50,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
ranarr

6

In [67]:
np.max(ranarr)

5

In [68]:
ranarr.max()

AttributeError: 'int' object has no attribute 'max'