# Exercise1

# NumPy Async Activities 

Now that you've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
#First, we need to import NumPy which is a library 
#that offers comprehensive mathematical functions, 
#random number generators, linear algebra routines, and more.


import numpy as np

#### Create an array of 10 zeros 

In [2]:
#To create an array of 10 zeroes,
#let's use the "zeros" function

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
#To create an array of 10 ones,
#let's use the "ones" function

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
#To create an array of 10 fives,
#let's create an array of 10 ones
#then multiply it by 5

np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [7]:
#Let's use the "arange" function to create an array
#and use 10 as the start of the interval
#and 51 as the end of the interval

np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [8]:
#Let's use the same code above and
#add a "step" of 2

np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [125]:
#Let's use the "arange" function to create an array
#Let's use the "reshape" function to create a 3x3 matrix

mx=np.arange(0,9).reshape(3,3)
mx

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [124]:
#The "eye" function is used to create an identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
#To generate a random number between 0 and 1,
#let's use "random.uniform"

np.random.uniform(0,1)

0.3654562240518713

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
#To generate an array of numbers from a standard normal distribution,
#let's use "random.normal"

np.random.normal(0,1,25)

array([ 0.42210309, -0.56420734, -0.66406656,  0.52296147, -1.11017909,
       -0.4424593 ,  0.21526674,  0.74997138, -0.60295072,  0.76918231,
       -0.55512111, -0.88878524, -0.31090365, -0.80285434,  0.06496613,
       -0.38075712, -0.71435841, -0.16358872,  0.35836695, -1.63383282,
       -0.70507645, -0.27885481, -0.59448471,  0.43897269,  0.1813575 ])

#### Create the following matrix:

In [123]:
#Let's use the "arange" function to create an array
#and use 1 and 101 as the start and end of the interval.
#To create a 10x10 matrix, let's use the "reshape" function,
#then divide the array by 100

np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [97]:
#Let's use the "linspace" function
#to create an array of linearly spaced points

np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [17]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [19]:
#Let's use "2:" to select rows 3-5
#and "1:" to select the columns 2-5

mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [20]:
#Let's use "[3,4]" since the output is on row 4, column 5

mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [22]:
#Let's use "0:3" to select rows 1-3
#and "1:2" to retain the column 2 only

mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [67]:
#To get the fifth row of the array, use the code below

mat[4:,0:]

array([[21, 22, 23, 24, 25]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [66]:
#To get the 4th and 5th row of the array, use the code below

mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [24]:
#To get the sum of all values in mat, 
#we use the NumPy "sum" function

np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [72]:
#To get the standard deviation of the values in mat, 
#we use the NumPy "std" function

np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [73]:
#To get the sum of all values in mat, 
#we use the NumPy "sum" function.
#Then let's use the "axis=0"
#to specify that we only want to get 
#the sum of all the columns

mat.sum(axis=0)

array([55, 60, 65, 70, 75])

<I><B> # ---End for NumPy